---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-w-disallowed-capability-should-fail
  
spec:
  containers:
    - name: test-container
      image: nginx
      securityContext:
        capabilities:
          add:
            - CHOWN
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-w-allowed-capability-should-pass
  
spec:
  containers:
    - name: test-container
      image: nginx
      securityContext:
        capabilities:
          add:
            - SYS_TIME
